<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class MigrationUpdate3 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::table('bis_job_applications', function (Blueprint $table) {
            $table->text('building_type')->nullable();
            $table->text('estimated_total_cost')->nullable();
            $table->text('last_action')->nullable();
            $table->text('electronically_filed')->nullable();
            $table->text('application_approved_on')->nullable();
            $table->text('doc_overview_uri')->nullable();
            $table->text('fees_paid_uri')->nullable();
            $table->text('crane_information_uri')->nullable();
            $table->text('after_hours_variance_permit_uri')->nullable();
            $table->text('items_required_uri')->nullable();
            $table->text('forms_received_uri')->nullable();
            $table->text('plan_examination_uri')->nullable();
            $table->text('virtual_job_folder_uri')->nullable();
            $table->text('all_permits_uri')->nullable();
            $table->text('all_comments_uri')->nullable();
            $table->text('schedule_a_uri')->nullable();
            $table->text('schedule_b_uri')->nullable();
            $table->text('plumbing_inspections_uri')->nullable();
            $table->text('co_summary_uri')->nullable();
            $table->text('co_preview_uri')->nullable();
            $table->text('print_letter_of_completion_uri')->nullable();
            $table->text('dob_now_inspections_url')->nullable();
            $table->boolean('job_application_type_a1_flag')->default(false);
            $table->boolean('job_application_type_a1_ot_flag')->default(false); 
            $table->boolean('job_application_type_a1_new_building_flag')->default(false);
            $table->boolean('job_application_type_a2_flag')->default(false);
            $table->boolean('job_application_type_full_demo_flag')->default(false);
            $table->boolean('job_application_type_a3_flag')->default(false);
            $table->boolean('job_application_type_subdivision_improved')->default(false);
            $table->boolean('job_application_type_sign')->default(false);
            $table->boolean('job_application_type_subdivision_condo')->default(false);
            $table->boolean('job_application_type_directive_14_acceptance_requested')->default(false);
            $table->text('sec_7_plans_page_count')->nullable();
            $table->text('sec_8_total_bldg_square_footage')->nullable();
            $table->text('sec_8_total_construction_floor_area')->nullable();
            $table->boolean('sec_8_horizontal')->default(false);
            $table->boolean('sec_8_vertical')->default(false);
            $table->boolean('sec_8_enlargement_proposed')->default(false);
            $table->boolean('landmark')->default(false);
            $table->text('landmark_docket_number')->nullable();
            $table->boolean('environ_restrictions')->default(false);
            $table->boolean('unmapped_cco')->default(false);
            $table->boolean('legalization')->default(false);
            $table->boolean('other_specify')->default(false);
            $table->boolean('filed_comply_local_law')->default(false);
            $table->boolean('restrict_dec_easement')->default(false);
            $table->boolean('zoning_exhibit_record')->default(false);
            $table->boolean('filed_to_address_vios')->default(false);
            $table->boolean('work_includes_lighting_fixture')->default(false);
            $table->boolean('work_fuel_burning')->default(false);
            $table->boolean('modular_construction_ny_state')->default(false);
            $table->boolean('modular_construction_ny_city')->default(false);
            $table->boolean('structural_peer_review_required')->default(false);
            $table->boolean('work_includes_permanent_removal')->default(false);
            $table->boolean('work_includes_partial_demo')->default(false);
            $table->boolean('structural_stability_affected')->default(false);
            $table->boolean('sec_10_in_compliance_with_NYCECC')->default(false);
            $table->boolean('sec_10_energy_analysis_on_another_job_number')->default(false);
            $table->boolean('sec_10_exempt_from_NYCECC')->default(false);
            $table->boolean('sec_10_utilizes_tradeoffs_different_major_systems')->default(false);
            $table->boolean('sec_10_utilizes_tradeoffs_single_major_system')->default(false);
            $table->boolean('sec_10_alteration_of_state_or_national')->default(false);
            $table->boolean('sec_10_cc_path_nycecc')->default(false);
            $table->boolean('sec_10_cc_path_ashare')->default(false);
            $table->boolean('sec_10_ea_tabular')->default(false);
            $table->boolean('sec_10_ea_rescheck')->default(false);
            $table->boolean('sec_10_ea_comcheck')->default(false);
            $table->boolean('sec_10_ea_energy_modeling')->default(false);
            $table->text('sec_11_job_description')->nullable();
            $table->text('sec_11_related_bis_job_numbers_uri')->nullable();
            $table->text('sec_11_primary_app_job_number')->nullable();
            $table->text('sec_12_zoning_characteristics_districts')->nullable();
            $table->text('sec_12_special_districts')->nullable();
            $table->text('sec_12_overlays')->nullable();
            $table->text('sec_12_map_no')->nullable();
            $table->text('sec_12_street_legal_width')->nullable();
            $table->text('sec_12_zoning_includes_tax_lots')->nullable();
            $table->boolean('sec_12_zoning_street_status_public')->default(false);
            $table->boolean('sec_12_zoning_street_status_private')->default(false);
            $table->boolean('sec_12_proposed_lot_details_corner')->default(false);
            $table->boolean('sec_12_proposed_lot_details_interior')->default(false);
            $table->boolean('sec_12_proposed_lot_details_through')->default(false);
            $table->text('sec_12_proposed_use')->nullable();
            $table->text('sec_12_proposed_use_zoning')->nullable();
            $table->text('sec_12_proposed_use_district')->nullable();
            $table->text('sec_12_proposed_use_FAR')->nullable();
            $table->text('sec_12_zoning_area_proposed_total')->nullable();
            $table->text('sec_12_district_area_proposed_total')->nullable();
            $table->text('sec_12_FAR_area_proposed_total')->nullable();
            $table->text('sec_12_zoning_area_existing_total')->nullable();
            $table->text('sec_12_district_area_existing_total')->nullable();
            $table->text('sec_12_FAR_area_existing_total')->nullable();
            $table->text('sec_12_proposed_lot_coverage')->nullable();
            $table->text('sec_12_proposed_lot_area')->nullable();
            $table->text('sec_12_proposed_lot_width')->nullable();
            $table->text('sec_12_proposed_yard_details_no_yards')->nullable();
            $table->text('sec_12_proposed_yard_front')->nullable();
            $table->text('sec_12_proposed_yard_rear')->nullable();
            $table->text('sec_12_proposed_yard_rear_equivalent')->nullable();
            $table->text('sec_12_proposed_yard_side1')->nullable();
            $table->text('sec_12_proposed_yard_side2')->nullable();
            $table->text('sec_12_proposed_other_perimeter_wall_height')->nullable();
            $table->text('sec_12_proposed_other_details_enclosed_parking')->nullable();
            $table->text('sec_12_proposed_other_details_number_of_parking_spaces')->nullable();
            $table->text('sec_13_occ_class_existing_text')->nullable();
            $table->boolean('sec_13_occ_class_2014_2008_code_designations')->default(false);
            $table->text('sec_13_occ_class_proposed_text')->nullable();
            $table->text('sec_13_con_class_existing_text')->nullable();
            $table->boolean('sec_13_con_class_2014_2008_code_designations')->default(false);
            $table->text('sec_13_con_class_proposed_text')->nullable();
            $table->text('sec_13_multi_dwelling_class_existing_text')->nullable();
            $table->text('sec_13_multi_dwelling_class_proposed_text')->nullable();
            $table->text('sec_13_building_height_existing_text')->nullable();
            $table->text('sec_13_building_height_proposed_text')->nullable();
            $table->text('sec_13_building_stories_existing_text')->nullable();
            $table->text('sec_13_building_stories_proposed_text')->nullable();
            $table->text('sec_13_dwelling_units_existing_text')->nullable();
            $table->text('sec_13_dwelling_units_proposed_text')->nullable();
            $table->boolean('sec_13_erected_pursuant_to_bc_2014')->default(false);
            $table->boolean('sec_13_erected_pursuant_to_bc_2008')->default(false);
            $table->boolean('sec_13_erected_pursuant_to_bc_1968')->default(false);
            $table->boolean('sec_13_erected_pursuant_to_bc_before_1968')->default(false);
            $table->boolean('sec_13_earliest_code_required_2014')->default(false);
            $table->boolean('sec_13_earliest_code_required_2008')->default(false);
            $table->boolean('sec_13_earliest_code_required_1968')->default(false);
            $table->boolean('sec_13_earliest_code_required_before_1968')->default(false);
            $table->boolean('sec_13_mixed_use_building')->default(false);
            $table->boolean('sec_14_fill_not_applicable')->default(false);
            $table->boolean('sec_14_fill_off_site')->default(false);
            $table->boolean('sec_14_fill_on_site')->default(false);
            $table->boolean('sec_14_fill_under_300_cubic_yds')->default(false);
            $table->boolean('sec_15_construction_equipment_chute')->default(false);
            $table->boolean('sec_15_construction_equipment_sidewalk_shed')->default(false);
            $table->boolean('sec_15_construction_equipment_fence')->default(false);
            $table->boolean('sec_15_construction_equipment_supported_scaffold')->default(false);
            $table->boolean('sec_15_construction_equipment_other')->default(false);
            $table->text('sec_16_size_of_cut_splays')->nullable();
            $table->text('sec_16_curbcut_text')->nullable();
            $table->text('sec_16_distance_from_nearest_corner')->nullable();
            $table->boolean('sec_18_fire_alarm_existing')->default(false);
            $table->boolean('sec_18_fire_alarm_proposed')->default(false);
            $table->boolean('sec_18_sprinkler_existing')->default(false);
            $table->boolean('sec_18_sprinkler_proposed')->default(false);
            $table->boolean('sec_18_fire_suppression_existing')->default(false);
            $table->boolean('sec_18_fire_suppression_proposed')->default(false);
            $table->boolean('sec_18_standpipe_existing')->default(false);
            $table->boolean('sec_18_standpipe_proposed')->default(false);
            $table->boolean('sec_20_tidal_wetlands')->default(false);
            $table->boolean('sec_20_freshwater_wetlands')->default(false);
            $table->boolean('sec_20_coastal_erosion_hazard')->default(false);
            $table->boolean('sec_20_urban_renewal')->default(false);
            $table->boolean('sec_20_fire_district')->default(false);
            $table->boolean('sec_20_flood_hazard')->default(false);
            $table->boolean('sec_20_substantial_improvement')->default(false);
            $table->boolean('sec_20_substantially_damaged')->default(false);
            $table->boolean('sec_20_floodshields')->default(false);
            $table->boolean('sec_21_affects_exterior')->default(false);
            $table->boolean('sec_21_involves_raising')->default(false);
            $table->boolean('sec_22_requires_asbestos_abatement')->default(false);
            $table->boolean('sec_23_purpose_advertising')->default(false);
            $table->boolean('sec_23_purpose_non_advertising')->default(false);
            $table->boolean('sec_23_type_illuminated')->default(false);
            $table->boolean('sec_23_type_non_illuminated')->default(false);
            $table->boolean('sec_23_illuminated_type_direct')->default(false);
            $table->boolean('sec_23_illuminated_type_flashing')->default(false);
            $table->boolean('sec_23_illuminated_type_indirect')->default(false);
            $table->boolean('sec_23_location_ground')->default(false);
            $table->boolean('sec_23_location_roof')->default(false);
            $table->boolean('sec_23_location_wall')->default(false);
            $table->text('sec_23_estimated_cost')->nullable();
            $table->text('sec_23_total_sq_ft')->nullable();
            $table->text('sec_23_height_above_curb')->nullable();
            $table->text('sec_23_height_above_roof')->nullable();
            $table->boolean('sec_23_inside_building_line')->default(false);
            $table->text('sec_23_inside_building_line_text')->nullable();
            $table->boolean('sec_23_owner_billed_for_annual_permit')->default(false);
            $table->boolean('sec_23_sign_tight_closed_or_solid')->default(false);
            $table->boolean('sec_23_changeable_copy')->default(false);
            $table->text('sec_23_sign_wording_text')->nullable();
            $table->boolean('sec_23_oac_interest')->default(false);
            $table->text('sec_23_oac_registration_number')->nullable();
            $table->boolean('sec_23_within_900')->default(false);
            $table->text('sec_23_within_900_distance')->nullable();
            $table->boolean('sec_23_within_200')->default(false);
            $table->text('sec_23_within_200_distance')->nullable();
            $table->text('sec_24_comments')->nullable();
            $table->boolean('sec_25_nb_a1')->default(false);
            $table->boolean('sec_25_directive_14')->default(false);
            $table->text('sec_26_name')->nullable();
            $table->text('sec_26_relationship_to_owner')->nullable();
            $table->text('sec_26_business_name')->nullable();
            $table->text('sec_26_business_phone')->nullable();
            $table->text('sec_26_business_address')->nullable();
            $table->text('sec_26_business_fax')->nullable();
            $table->text('sec_26_email')->nullable();
            $table->text('sec_26_owner_type')->nullable();
            $table->text('sec_27_metes_and_bounds_text')->nullable();
            $table->text('sec_27_metes_and_bounds_running_thence_1')->nullable();
            $table->text('sec_27_metes_and_bounds_thence_1')->nullable();
            $table->text('sec_27_metes_and_bounds_running_thence_2')->nullable();
            $table->text('sec_27_metes_and_bounds_thence_2')->nullable();
            $table->text('sec_27_metes_and_bounds_running_thence_3')->nullable();
            $table->text('sec_27_metes_and_bounds_thence_3')->nullable();
            $table->text('sec_27_metes_and_bounds_running_thence_4')->nullable();
            $table->text('sec_27_metes_and_bounds_thence_4')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
